Use HCL syntax
suzuki-shunsuke/tfcmt pull request #146
Opened 2021-11-19 10:14 UTC by dtaniwaki

Using HCL syntax for terraform output is easier to read.

Ref: https://github.com/hashicorp/terraform-github-actions/issues/153

2021-11-19 22:55 UTC, riosje approved these changes

2021-11-20 02:51 UTC, suzuki-shunsuke commented
Thank you for your contribution!

2021-11-20 02:52 UTC, suzuki-shunsuke requested changes
CI failed. Please check.
https://github.com/suzuki-shunsuke/tfcmt/runs/4271305732?check_suite_focus=true

2021-11-20 03:58 UTC, suzuki-shunsuke approved these changes
Thanks!

2021-11-20 03:59 UTC, merged

2021-11-20 04:11 UTC, suzuki-shunsuke commented
The prerelease version [v2.1.0-0](https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v2.1.0-0) has been released.

2021-11-25 10:49 UTC, suzuki-shunsuke commented
[v2.1.0](https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v2.1.0) has been released.